DROP TABLE IF EXISTS books;

CREATE TABLE books (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(50) NOT NULL,
    description VARCHAR(255) NOT NULL,
    price DECIMAL (10, 2) NOT NULL,
    cover VARCHAR(255) NULL
);